{{- if and .Values.security.secrets.enabled .Values.security.secrets.createClusterSecretStore }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: kubunity-cluster-secret-store
  labels:
    {{- include "kubunity.labels" . | nindent 4 }}
spec:
  provider:
    {{- if eq .Values.security.secrets.backend.type "vault" }}
    vault:
      server: {{ .Values.security.secrets.backend.vault.server | quote }}
      path: {{ .Values.security.secrets.backend.vault.path | quote }}
      version: {{ .Values.security.secrets.backend.vault.version | quote }}
      auth:
        tokenSecretRef:
          name: {{ .Values.security.secrets.backend.vault.auth.tokenSecretRef.name | quote }}
          key: {{ .Values.security.secrets.backend.vault.auth.tokenSecretRef.key | quote }}
          namespace: {{ .Values.security.secrets.backend.vault.auth.tokenSecretRef.namespace | quote }}
    {{- else if eq .Values.security.secrets.backend.type "aws" }}
    aws:
      service: {{ .Values.security.secrets.backend.aws.service | quote }}
      region: {{ .Values.security.secrets.backend.aws.region | quote }}
    {{- else if eq .Values.security.secrets.backend.type "azure" }}
    azurekv:
      vaultUrl: {{ .Values.security.secrets.backend.azure.vaultUrl | quote }}
    {{- else if eq .Values.security.secrets.backend.type "gcp" }}
    gcpsm:
      projectID: {{ .Values.security.secrets.backend.gcp.projectID | quote }}
    {{- end }}
{{- end }}
