# Profil Kubunity : Edge & K3s (Empreinte mémoire ultra-légère)
cluster:
  name: "edge-node-01"
  environment: "edge"
  profile: "edge"

security:
  kyverno:
    enabled: true
    validationFailureAction: "Audit"
    policies:
      disallowRoot:
        enabled: true
      requireResources:
        enabled: false
      disallowLatestTag:
        enabled: true
      autoGenerateNetworkPolicies:
        enabled: true
      disallowPrivilegeEscalation:
        enabled: true
      disallowHostNamespaces:
        enabled: false
      requireReadOnlyRootFilesystem:
        enabled: false
      restrictClusterAdminBindings:
        enabled: true

  secrets:
    enabled: true
    createClusterSecretStore: false

gitops:
  enabled: false
