# Profil Kubunity : Cloud Entreprise (EKS, GKE, AKS, OpenShift)
cluster:
  name: "prod-cloud-eu-west-1"
  environment: "production"
  profile: "cloud"
  region: "eu-west-1"

security:
  kyverno:
    enabled: true
    validationFailureAction: "Enforce" # Blocage strict en production
    policies:
      disallowRoot:
        enabled: true
      requireResources:
        enabled: true
      disallowLatestTag:
        enabled: true
      autoGenerateNetworkPolicies:
        enabled: true
      disallowPrivilegeEscalation:
        enabled: true
      disallowHostNamespaces:
        enabled: true
      requireReadOnlyRootFilesystem:
        enabled: true
      restrictClusterAdminBindings:
        enabled: true

  secrets:
    enabled: true
    createClusterSecretStore: true
    backend:
      type: "aws"
      aws:
        region: "eu-west-1"
        service: "SecretsManager"

  vulnerabilityScanner:
    enabled: true

networking:
  cilium:
    enabled: true
    defaultClusterwidePolicy:
      enabled: true

observability:
  openTelemetryCollector:
    enabled: true
    mode: "deployment"
  openobserve:
    enabled: true
    endpoint: "http://o2-openobserve-router.openobserve.svc:5080/api/default"
    streamName: "k8s_cloud_telemetry"
  kusanagi:
    enabled: true
    openobserve:
      enabled: true
    ingress:
      enabled: true
      className: "traefik"
      hosts:
        - host: "kusanagi.prod.example.com"
          paths:
            - path: /
              pathType: Prefix

gitops:
  enabled: true
  provider: "argocd"
  appOfApps:
    enabled: true
    repoURL: "https://github.com/org/kubunity-fleet-prod.git"
    targetRevision: "main"
    basePath: "clusters/prod"
