# Profil Kubunity : Développement Local (Kind / K3d / Minikube)
cluster:
  name: "local-dev"
  environment: "development"
  profile: "dev"

security:
  kyverno:
    enabled: true
    validationFailureAction: "Audit"
    policies:
      disallowRoot:
        enabled: true
      requireResources:
        enabled: false
      disallowLatestTag:
        enabled: false
      autoGenerateNetworkPolicies:
        enabled: false
      disallowPrivilegeEscalation:
        enabled: false
      disallowHostNamespaces:
        enabled: false
      requireReadOnlyRootFilesystem:
        enabled: false
      restrictClusterAdminBindings:
        enabled: false

  secrets:
    enabled: false

observability:
  kusanagi:
    enabled: true # Pratique pour tester le dashboard en local
    service:
      type: "NodePort"

goldenPaths:
  enabled: true
  tenants:
    - name: "demo-app"
      environment: "development"
      quotas:
        requestsCpu: "1"
        requestsMemory: "1Gi"
        limitsCpu: "2"
        limitsMemory: "2Gi"
