{{- if and .Values.observability.openobserve.enabled .Values.observability.openobserve.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubunity.fullname" . }}-openobserve-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubunity.labels" . | nindent 4 }}
    app.kubernetes.io/component: "openobserve-auth"
type: Opaque
stringData:
  authorization: {{ .Values.observability.openobserve.auth.authorizationHeader | quote }}
  username: {{ .Values.observability.openobserve.auth.username | default "root@example.com" | quote }}
  password: {{ .Values.observability.openobserve.auth.password | default "" | quote }}
{{- end }}
